### ISSUE TITLE
Add SmartThings API framework dependency

### ISSUE THREAD

**Issue by Laptopmini** [SmartThingsCommunity/st-schema-nodejs#25]
This SDK could benefit from having a SmartThings API framework as a dependency to simplify making calls from the connector to SmartThings, such as when trying to update the state of a device outside of a connector interaction.

This could simply be a suggestion in the README, as these calls are not a requirement for integrations to operate, thus the package could be optional. 

Unfortunately, there is no public SmartThings API framework at the moment (which isnt outdated). The one from https://github.com/SmartThingsCommunity/smartapp-sdk-nodejs should be extracted, and both SDKs should make it a dependency (separately maintained).

**Comment by workingmonk** [comment]
ST Schema currently does not issue tokens that can be used with the ST API. ST schema currently serves to integrate partner devices to ST Platform instead of exposing ST devices to partners.

**Comment by Laptopmini** [comment]
Then what is the reciprocal access token for?

https://smartthings.developer.samsung.com/docs/devices/smartthings-schema/smartthings-schema-reference.html#Reciprocal-access-token

**Comment by workingmonk** [comment]
To send the state of the partner device back to ST Schema platform. Those tokens do NOT give you access to user's devices.

**Comment by Laptopmini** [comment]
Should we provide the necessary methods for the endpoints that are available?
